feat(CSS): support CSS Parts #116
AlaskaAirlines/auro-dropdown pull request #117
Opened 2022-04-25 14:33 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #116

## Summary:

This change adds `part=""` attributes to the main template elements.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-04-25 15:47 UTC, blackfalcon requested changes
There are no updates to the JSDOcs to illustrate this update in the API and an example in the demo should be considered.

2022-04-25 16:47 UTC, jason-capsule42 commented
> There are no updates to the JSDOcs to illustrate this update in the API and an example in the demo should be considered.

JS Doc information added. 

I want to discuss the demo examples idea for CSS Parts. I'm hesitant.... We haven't been doing demo examples showing custom CSS in other components as far as I know. Let's discuss in our planning meeting.

2022-04-25 21:27 UTC, blackfalcon approved these changes

2022-04-26 14:22 UTC, merged

2022-04-26 14:26 UTC, blackfalcon commented
:tada: This PR is included in version 2.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/2.3.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v2.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: