feat(examples): improve example JS code implementation
AlaskaAirlines/auro-dropdown pull request #148
Opened 2022-08-24 18:55 UTC by jason-capsule42

# Alaska Airlines Pull Request

## Summary:

This POC aims to solve the following problems:

- When adding a new example with example specific JS code, an update must also be made to AuroDocSite to include and execute the new JS file. This has resulted in multiple broken examples on the doc site as we update components but neglect to update the doc site.
- When executing examples with example specific JS code in a local host they will run correctly but then fail when deployed to the docsite do to race conditions where the component or it's dependencies are not yet ready to execute the examples JS code.

Solutions/changes

- Add a new `examples.js` file. Make the docsite only point to this one file rather than pointing to each individual example JS file. This way we can make updates to `examples.js` without any need to update AuroDocSite. Inside `example.js` we do two things:
  - Declare a function that will initialize an example in order to assure the page is ready (and retry if not)
  - Execute the necessary example JS when the component is ready.
  
My proposed solution preserves the separate example specific JS files so that we can reference them in the docs where needed. 

Adding a new API feature requiring custom JS for the example would now only require work within the component repo for it to work on the doc site.

The only caveat is that AuroDocSite would need an initial update to start running `examples.js` for a repro rather than what it currently does which is run each separate example JS file individually.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-08-25 18:16 UTC, blackfalcon commented
Was there an issue for this PR that we should be referencing for this work? Also, what part of the examples is this fixing? I am unable to determine what needs to be reviewed.

2022-08-25 22:01 UTC, jason-capsule42 commented
> Was there an issue for this PR that we should be referencing for this work? Also, what part of the examples is this fixing? I am unable to determine what needs to be reviewed.

@blackfalcon 

The issue with the race condition loading was discovered while working on this combobox ticket: https://github.com/AlaskaAirlines/auro-combobox/issues/64

The issue will only reproduce on the actual docsite, not locally. And even then, it only reproduces part of the time due to the race condition. This should make it work 100% of the time as well as remove the requirement to update the docsite when adding new examples.

I did my POC here because it was another repo that would need this implemented and it wasn't something Jordan was already mucking around in.

If this is something we agree to move forward with, I can put together a proper ticket to commit against.

I chose to use feature rather than fix because it felt like an "engineering feature" even though it wasn't a user feature. I'm not particularly attached.

2022-08-26 00:06 UTC, blackfalcon approved these changes, later dismissed

2022-08-26 00:06 UTC, blackfalcon commented
Please update the commit from `feat` to `fix` and you are golden!

2022-08-30 14:23 UTC, blackfalcon requested changes
This is not a feature change to the element. The scope of the changes is only to docs and examples. Please update the commit messages to use `docs` as the prefix. 

A release is not required for these updates.

2022-09-01 20:49 UTC, blackfalcon approved these changes

2022-09-02 05:14 UTC, merged

2022-09-02 19:06 UTC, blackfalcon commented
:tada: This PR is included in version 2.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/2.9.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v2.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: