Irmaku/update node18
AlaskaAirlines/auro-dropdown pull request #192
Opened 2023-05-05 13:07 UTC by irma-kurnia-alaska

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Resolves: #188 , #189 , #190 , #191 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-05-05 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/AlaskaAirlines/auro-dropdown?pullRequest=192) <br/>All committers have signed the CLA.

2023-05-16 21:57 UTC, blackfalcon requested changes

2023-05-16 21:57 UTC, blackfalcon commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
```suggestion
      description: List out the steps to reproduce the behavior and include screenshots
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
```

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "lit-html": "^2.7.3"
```suggestion

```

Uninstall this dependency, this is no longer needed with Lit2.0

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "babel-loader": "^9.1.2",
Remove dependency

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "marked": "^5.0.0",
Remove dependency

2023-05-16 21:57 UTC, blackfalcon commented on package.json
>      "prismjs": "^1.29.0",
Remove dependency

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "build:watch": "nodemon -e scss,js --watch src --exec npm run build:dev:assets",
```suggestion
    "build:watch": "nodemon -e scss,js,html --watch src --watch apiExamples --exec npm run build:dev:assets",
```

Undo this change. The previous script was correct.

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "cssLint": "stylelint \"./src/*.css\"",
Revert

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "linters": "npm-run-all cssLint esLint",
Revert

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> +    "build": "npm-run-all build:sass sass:render cssLint dist:js bundler postinstall build:api types",
```suggestion
    "build": "npm-run-all build:sass sass:render dist:js bundler postinstall build:api types",
```

2023-05-16 21:57 UTC, blackfalcon commented on src/style.scss
> +  box-shadow: -2px 0 5px 2px rgb(0 0 0 / .08), 0 2px 5px 1px rgb(0 0 0 / .08);
Why was this changed? Please revert.

2023-05-16 21:57 UTC, blackfalcon commented on package.json
> -    "build:markdownDocs": "node scripts/generateDocs.js",
Revert this removed script and update to the following. 

```
"build:markdownDocs": "node scripts/generateDocs.js",
```

2023-05-16 21:57 UTC, blackfalcon commented on .husky/pre-commit
> +./node_modules/.bin/npm-run-all linters test
```suggestion
./node_modules/.bin/npm-run-all preCommit test linters postinstall
```

2023-05-16 21:57 UTC, blackfalcon commented on .stylelintrc
> +    "selector-type-no-unknown": null
Please revert the whole file. It should be the same as this resource. 

https://github.com/AlaskaAirlines/WC-Generator/blob/master/template/.stylelintrc

2023-05-17 14:13 UTC, irma-kurnia-alaska commented
Hi @blackfalcon, 

I will updated as you mention feedback for this PR. Thank you for your feedback.

2023-05-24 21:33 UTC, blackfalcon approved these changes

2023-05-24 21:33 UTC, merged

2023-05-24 21:35 UTC, blackfalcon commented
:tada: This PR is included in version 2.9.8 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/2.9.8)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v2.9.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: