feat(label): add support for dropdown label
AlaskaAirlines/auro-dropdown pull request #28
Opened 2021-11-22 18:59 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #26

## Summary:

This change adds support for a label on `auro-dropdown`.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-11-23 05:06 UTC, blackfalcon requested changes

2021-11-23 05:06 UTC, blackfalcon commented on src/auro-dropdown.js
> +          <div>
Wouldn't be easier to manage if this was a slot versus a property? Like https://github.com/AlaskaAirlines/auro-input/blob/main/src/auro-input.js#L294-L299

2021-11-23 05:06 UTC, blackfalcon commented on src/style.scss
> +#label {
I realize there are some poor practices with this CSS, but maybe curb the madness and make this a class instead?

2021-11-23 05:06 UTC, blackfalcon commented on src/auro-dropdown.js
> +      label:         { type: String }
If you make this a slot then this is not needed.

2021-11-23 05:06 UTC, blackfalcon commented on src/auro-dropdown.js
> +          <div>
I am not seeing a test to support this property or if statement? Property or slot, there needs to be an addition to the JSDoc header.

2021-11-23 08:06 UTC, jason-capsule42 commented on src/auro-dropdown.js
> +          <div>
> Wouldn't be easier to manage if this was a slot versus a property? Like https://github.com/AlaskaAirlines/auro-input/blob/main/src/auro-input.js#L294-L299

No, making this a slot opens the door for someone to put any HTML they want into the slot. There should never be anything other than a simple text string entered and using an attribute enforces that.

2021-11-23 08:07 UTC, jason-capsule42 commented on src/style.scss
> +#label {
There is only ever going to be one #label inside the shadow DOM container. Why would we want to use a class here?

2021-11-23 08:08 UTC, jason-capsule42 commented on src/auro-dropdown.js
> +      label:         { type: String }
Same comment as above - slot is to open ended. There should only ever be a simple string defined here. Using the attribute enforces that where a slot makes it possible to add anything they want to a label which we do not support.

2021-11-23 14:33 UTC, blackfalcon commented on src/auro-dropdown.js
> +          <div>
That's not necessarily true. The discussion around a users ability to add in things like auro-icon https://github.com/AlaskaAirlines/auro-input/issues/59

2021-11-23 14:46 UTC, blackfalcon commented on src/auro-dropdown.js
> +      label:         { type: String }
Same reply https://github.com/AlaskaAirlines/auro-input/issues/59

2021-11-23 14:54 UTC, blackfalcon commented on src/style.scss
> +#label {
As a general rule in CSS, ID selectors are never preferred. We are in the scope of an encapsulated UI, the specificity of an ID is not necessary. 

I am not 100% as to the state of this repo, but I am also pretty sure this is in violation with our stylelint rules https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-id-pattern/README.md#options

from https://github.com/stylelint/stylelint-config-standard/blob/main/index.js#L138 that is extended from stylelint-config-standard-scss

2021-11-23 19:47 UTC, blackfalcon requested changes
I also noticed that the HTML template has a wrapping div that I am not sure is needed? 

```html
<div id="defaultExample">
```

2021-11-23 19:47 UTC, blackfalcon commented on test/auro-dropdown.test.js
> +      <auro-dropdown cssClass="testClass"></auro-dropdown>
This isn't exactly a valid test. There is no `cssClass` attribute in the API.

2021-11-23 19:47 UTC, blackfalcon commented on test/auro-dropdown.test.js
> +  it('auro-dropdown programatically show and hide', async () => {
```suggestion
  it('auro-dropdown programmatically show and hide', async () => {
```

2021-11-23 21:45 UTC, blackfalcon approved these changes

2021-11-23 21:58 UTC, merged

2022-01-11 02:29 UTC, blackfalcon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/1.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: