feat(helperText): add support for helper text
AlaskaAirlines/auro-dropdown pull request #29
Opened 2021-11-22 19:15 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #27

## Summary:

This change adds support for helperText at the bottom of the dropdown.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-11-23 05:12 UTC, blackfalcon requested changes

2021-11-23 05:12 UTC, blackfalcon commented on src/auro-dropdown.js
> +      ` : undefined}
Is there a need to support error text? Also, I'd recommend that this use a `slot` versus a property like we do with auro-input https://github.com/AlaskaAirlines/auro-input/blob/main/src/auro-input.js#L302-L311

2021-11-23 05:12 UTC, blackfalcon commented on src/style.scss
> +}
To make more of this code portable to an official Auro version, we should use proper classes when new code is added.

2021-11-23 05:12 UTC, blackfalcon commented on src/style.scss
> +}
See the previous comment.

2021-11-23 05:12 UTC, blackfalcon commented on src/auro-dropdown.js
> +      helperText:    { type: String }
If converted to a `slot`, this property is not needed.

2021-11-23 05:12 UTC, blackfalcon commented on src/auro-dropdown.js
> +      ` : undefined}
Tests? JSDocs reference?

2021-11-23 07:56 UTC, jason-capsule42 commented on src/auro-dropdown.js
> +      ` : undefined}
Yes, we need to support error text.

We should not use a slot because we do not ever want to have anything other than a raw text string entered for helperText. In no case should any custom HTML be entered into helperText. Using a slot makes the helperText to open ended.

2021-11-23 08:02 UTC, jason-capsule42 commented on src/style.scss
> +}
I don't know what is wrong with this selector. Please be specific about what is wrong with this selector.

I'm not finding anything here that says anything is wrong. http://auro.alaskaair.com/css/conventions

2021-11-23 14:56 UTC, blackfalcon commented on src/auro-dropdown.js
> +      ` : undefined}
Restricting users to only a string is not a specification I am aware of? Also, this is in conflict with the decision to open this up to a slot in auro-input https://github.com/AlaskaAirlines/auro-input/blob/main/src/auro-input.js#L305

2021-11-23 14:57 UTC, blackfalcon commented on src/style.scss
> +}
I am unsure why this is a debate? Using an ID is not considered a best practice and is never used in any of the other elements?

2021-11-23 23:54 UTC, blackfalcon approved these changes

2021-11-24 16:21 UTC, merged

2022-01-11 02:30 UTC, blackfalcon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/1.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: