refactor(generator migration): migrate repo to latest generator build
AlaskaAirlines/auro-dropdown pull request #32
Opened 2021-11-30 04:12 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #31 

## Summary:

This change updates the repository to base off of generator v3.11.1

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [x] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-11-30 18:44 UTC, blackfalcon requested changes

2021-11-30 18:44 UTC, blackfalcon commented on .github/settings.yml
> +  description: Custom element that ....
Please update description

2021-11-30 18:44 UTC, blackfalcon commented on .github/workflows/testPublish.yml
> +          node-version: 14
This should be `16`?

2021-11-30 18:44 UTC, blackfalcon commented on README.md
> +`<auro-dropdown>` is a [HTML custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) for the purpose of ...
Please update to use the description we want to go live with.

2021-11-30 18:44 UTC, blackfalcon commented on README.md
> +
Please add use cases or delete, up to you.

2021-11-30 18:44 UTC, blackfalcon commented on docs/api.md
> +| `show` | `(): void` |
These should be `@private` methods.

2021-11-30 18:44 UTC, blackfalcon commented on src/auro-dropdown.js
> +       */
Nit-pick, please group the non-private and the private props separately for easy read/scanning.

2021-11-30 19:27 UTC, jason-capsule42 commented on .github/settings.yml
> +  description: Custom element that ....
The whole readme needs to be done and will be handled outside of the repoUpgrade.

2021-11-30 19:28 UTC, jason-capsule42 commented on README.md
> +`<auro-dropdown>` is a [HTML custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) for the purpose of ...
Same comment as above.

2021-11-30 19:28 UTC, jason-capsule42 commented on README.md
> +
Same comment as above.

2021-11-30 19:29 UTC, jason-capsule42 commented on docs/api.md
> +| `show` | `(): void` |
These are not private intentionally. Hide() is necessary in cases where someone wants to programmatically close the dropdown from within the dropdown content. (e.g. dropdown menu - clicking a menu item selects the value but also closes the dropdown)

I am not entirely sure if show() should be exposed or not. Conversation for outside of the repoUpgrade though.

2021-11-30 20:18 UTC, blackfalcon commented on docs/api.md
> +| `show` | `(): void` |
Can you please add descriptions to the JSDoc?

2021-11-30 20:20 UTC, blackfalcon commented on README.md
> +
These are the things that get easily forgotten later as they will not be in another pull request and there is a lot of other things to review. 

If not addressed now, I'd like to at least see a new issue added to the repo about completing the documentation for the README.md file.

2021-11-30 20:47 UTC, braven112 commented on README.md
> +
Heads up, I added a bullet point to the #8 to double check this and referenced this PR.

2021-12-02 15:32 UTC, blackfalcon approved these changes

2021-12-02 16:05 UTC, merged

2022-01-11 02:30 UTC, blackfalcon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/1.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: