Jbaker/onDark/#30
AlaskaAirlines/auro-dropdown pull request #34
Opened 2021-11-30 07:35 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #30 

## Summary:

This change adds styles for `onDark` and updates the demo docs so all API examples show the `onDark` version.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-12-03 00:18 UTC, blackfalcon requested changes

2021-12-03 00:18 UTC, blackfalcon commented on README.md
> +  </span>
For default slots, there is no need to wrap this content in `span` elements. 

```suggestion
  Lorem ipsum solar
```

2021-12-03 00:18 UTC, blackfalcon commented on README.md
> +  </span>
This goes for all code examples, not going to be repetitive in all the code.

2021-12-03 00:18 UTC, blackfalcon commented on apiExamples/basicButton.html
> +</auro-dropdown>
There should always be a line after. This is part of the editor config

https://github.com/AlaskaAirlines/auro-dropdown/blob/05b568687e90f1db56a58413648ca4f1c8e74da6/.editorconfig#L6-L10

2021-12-03 00:18 UTC, blackfalcon commented on apiExamples/label.html
> +  label="Label"
What is the purpose of this `label` property when there is a `label` slot?

2021-12-03 00:18 UTC, blackfalcon commented on demo/style.scss
> +  font-weight: 500;
Why is this font-weight set here? From what I can see, this only has an effect on the content that appears in the dropdown trigger? 

If that is a design spec, that should be set in the element's Sass, not in an external stylesheet?

2021-12-03 00:18 UTC, blackfalcon commented on src/style.scss
> +  #trigger {
We should not be creating CSS selectors based on IDs. This would apply to all cases of `#trigger`.

2021-12-03 00:37 UTC, jason-capsule42 commented on apiExamples/basicButton.html
> +</auro-dropdown>
Odd that VS Code added the EOF line on some of these but not all of them when saved. I resaved all the files to make sure they got it.

2021-12-03 00:39 UTC, jason-capsule42 commented on apiExamples/label.html
> +  label="Label"
Was left over in the demo example when making the earlier change to switch to a slot. Removing it now.

2021-12-03 00:40 UTC, jason-capsule42 commented on demo/style.scss
> +  font-weight: 500;
Because a table is used to create a two column layout with light and onDark renderings side by side the styles in WCSS are inherited.

The WCSS has a style for this same selector string that applied a lighter font weight which shows up in the demo page. This is just over-riding that and restoring it to the default text font-weight.

2021-12-03 00:43 UTC, jason-capsule42 commented on src/style.scss
> +  #trigger {
While classes are generally better than IDs in pure CSS, in cases where JS also is doing a querySelector for the id or class it makes sense to use an ID rather than using a class which returns an array of items that you then have to select the first in the array and trust it's the right one.

2021-12-03 00:47 UTC, blackfalcon commented
Is there a recent version of this posted as a demo that @leeejune can fully compare to the blueprint?

2021-12-03 00:50 UTC, blackfalcon commented on demo/style.scss
> +  font-weight: 500;
Well, this isn't going to fix that issue. The auro docsite will have that same reference and then we will have to hack on the docsite CSS too. 

We should correct this issue at the source so that it's addressed correctly.

2021-12-03 00:56 UTC, blackfalcon commented on src/style.scss
> +  #trigger {
There is a case to be had that keeping a healthy separation between style and functionality will win out in the end. E.g. one day we decide to change the name of the ID that the JS function is looking for. You will then have to update the CSS as well. That's an anti-pattern. 

SIngle responsibility states this differently. Having an ID for a function keeps that isolated to that single responsibility and the class selector keeps that isolated to that contract with the CSS.

2021-12-03 01:09 UTC, jason-capsule42 commented
> Is there a recent version of this posted as a demo that @leeejune can fully compare to the blueprint?

Yes, it's in the original ticket and she had already looked at it before the PR.

https://auro-dropdown-with-ondark.surge.sh/

2021-12-03 16:31 UTC, blackfalcon commented
> > Is there a recent version of this posted as a demo that @leeejune can fully compare to the blueprint?
> 
> Yes, it's in the original ticket and she had already looked at it before the PR.
> 
> https://auro-dropdown-with-ondark.surge.sh/

That link is out of date with the current UI of the demo page. To maintain a record of her design approval, I have started to include her in the PRs.

2021-12-03 17:26 UTC, jason-capsule42 commented on src/style.scss
> +  #trigger {
I've updated it to use both the ID for JS and class for CSS.

2021-12-03 17:26 UTC, blackfalcon commented on src/auro-dropdown.js
> +        <div class="trigger-content-wrapper">
I am assuming that you made this change and others like it because of feedback from Stylelint? This is something I ran into recently as well. 

While this is a common rule, this does not follow the convention that has been adopted throughout Auro. 

https://auro.alaskaair.com/css/conventions#:~:text=Naming%20convention

2021-12-03 17:26 UTC, jason-capsule42 commented on src/auro-dropdown.js
> +        <div class="trigger-content-wrapper">
This is based on our stylelint rules.

2021-12-03 17:29 UTC, blackfalcon commented on src/style.scss
> +  &:hover {
All hover states should be within a `@media (hover: hover)` [ref](https://css-tricks.com/solving-sticky-hover-states-with-media-hover-hover/)

2021-12-03 18:22 UTC, jason-capsule42 commented on src/style.scss
> +  &:hover {
Updated per feedback.

2021-12-03 19:28 UTC, jason-capsule42 commented on demo/style.scss
> +  font-weight: 500;
I agree we should correct it in the doc site. But I also think we should leave it here as well.

Anyone working on this locally is going to think something is wrong with the styles because the local demo won't render correctly.

2021-12-03 19:32 UTC, blackfalcon commented on src/auro-dropdown.js
> +        document.addEventListener('click', offClick);
yeah, that makes sense.

2021-12-03 19:36 UTC, blackfalcon commented on demo/style.scss
> +  font-weight: 500;
Please create a story in the DocSite and reference this thread so that we don't lose sight of this. I still think that you should remove this as it sets an incorrect expectation from the demo. 

The demo should only show what the element does. 

We will want to address the DocSite rendering of this issue prior to this element'e release so that we are confident that it will work there as expected. 

FYI, the code we need to address will be coming from WCSS. Both these element's and the docsite share dependencies. I am pretty sure... the docsite is a little bit of a mess with its markdown rendering.

2021-12-03 19:37 UTC, blackfalcon commented on src/auro-dropdown.js
> +        <div class="trigger-content-wrapper">
So right... the StyleLint rules missed the fact that this is contradicting our predefined CSS best practices. So I would argue that we need to remove this from StyleLint and use the pre-defined standard.

2021-12-03 19:38 UTC, blackfalcon requested changes
Additional comments.

2021-12-03 19:39 UTC, jason-capsule42 commented on src/auro-dropdown.js
> +        <div class="trigger-content-wrapper">
I'll change the local lint rule to camelCase and revert the changes.

2021-12-07 18:13 UTC, jason-capsule42 commented
Updated surge demo: dropdown-with-ondark-update4.surge.sh

2021-12-07 19:58 UTC, blackfalcon requested changes
I think we need to re-think this demo a little. There are a lot of examples in a very cramped space. The concept of `onDark` is secondary and I think we need to treat is as such. 

I'd suggest we focus on the primary examples and move the `onDark` versions to the lower half of the view and reduce the number of examples. There is no need to showcase every option possible. 

As for the primary examples, I would like to beef these up to really showcase that anything can be put in there. Maybe an image? Using the auro-menu? Maybe even something like https://auro.alaskaair.com/components/auro/checkbox#:~:text=See%20code-,Working%20example,-The%20following%20example

The example under **Example using hide method programmatically** probably needs to be moved up. When you select that one, because it's at the bottom, but dropdown moves up. 

That being said, we need to speak to that specifically. That is a slightly unexpected behavior and unless we talk about it, it may be seen as a defect.

2021-12-07 19:58 UTC, blackfalcon commented on demo/style.scss
> +[class^="exampleWrapper"] {
We shouldn't be doing this. None of the other demos add space around the gray slash background. The purpose of this is that we are only showing exactly what space the element will take up in any UI. 

While I agree that this may make the demos look a little weird, I am all for revisiting this, but I feel it's inappropriate as a one-off in this element.

2021-12-07 20:02 UTC, jason-capsule42 commented
> I think we need to re-think this demo a little. There are a lot of examples in a very cramped space. The concept of `onDark` is secondary and I think we need to treat is as such.
> 
> I'd suggest we focus on the primary examples and move the `onDark` versions to the lower half of the view and reduce the number of examples. There is no need to showcase every option possible.
> 
> As for the primary examples, I would like to beef these up to really showcase that anything can be put in there. Maybe an image? Using the auro-menu? Maybe even something like https://auro.alaskaair.com/components/auro/checkbox#:~:text=See%20code-,Working%20example,-The%20following%20example
> 
> The example under **Example using hide method programmatically** probably needs to be moved up. When you select that one, because it's at the bottom, but dropdown moves up.
> 
> That being said, we need to speak to that specifically. That is a slightly unexpected behavior and unless we talk about it, it may be seen as a defect.



> I think we need to re-think this demo a little. There are a lot of examples in a very cramped space. The concept of `onDark` is secondary and I think we need to treat is as such.
> 
> I'd suggest we focus on the primary examples and move the `onDark` versions to the lower half of the view and reduce the number of examples. There is no need to showcase every option possible.
> 
> As for the primary examples, I would like to beef these up to really showcase that anything can be put in there. Maybe an image? Using the auro-menu? Maybe even something like https://auro.alaskaair.com/components/auro/checkbox#:~:text=See%20code-,Working%20example,-The%20following%20example
> 
> The example under **Example using hide method programmatically** probably needs to be moved up. When you select that one, because it's at the bottom, but dropdown moves up.
> 
> That being said, we need to speak to that specifically. That is a slightly unexpected behavior and unless we talk about it, it may be seen as a defect.

Scope has creeped completely out of control on this PR. The PR os supposed to be strictly for adding the styles and demo examples for `onDark`. While I'm open to discussing these ideas we need to reign in the creep here. None of these ideas pertain to the actual creation of the onDark styles.

Let's create separate tickets for the ideas you have and get the style work itself buttoned it.

2021-12-07 20:05 UTC, blackfalcon approved these changes

2021-12-07 20:06 UTC, merged

2022-01-11 02:29 UTC, blackfalcon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dropdown/v/1.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dropdown/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: