fix(helptext): update slot name #75
AlaskaAirlines/auro-dropdown pull request #76
Opened 2022-02-11 18:53 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #75 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-02-17 21:19 UTC, jason-capsule42 requested changes

2022-02-17 21:19 UTC, jason-capsule42 commented on scripts/generateDocs.js
> -
This shouldn't be removed. We put the comment at the top of the readme about the compiled comment and this should be left in place.

2022-02-17 21:19 UTC, jason-capsule42 commented on src/auro-dropdown.js
> + * @slot helpText - Defines the content of the helpText.
This makes it a breaking change and needs to have the commit comment to go with that.

I'm not really sure why this change needs to happen. This whole PR seems to really revolve around the changing `helperText` to `helpText` which I am unsure justifies implementing a breaking change to the API.

2022-02-18 00:25 UTC, blackfalcon commented on src/auro-dropdown.js
> + * @slot helpText - Defines the content of the helpText.
Updated PR to release v2.0

> I'm not really sure why this change needs to happen.

This slot is inconsistent with other input elements that share a similar slot. This was a miss on my part from the initial PR to release this, so this needs to be corrected.

2022-03-01 02:32 UTC, blackfalcon commented on scripts/generateDocs.js
> -
This issue is to be discussed in a larger forum.

2022-03-02 22:56 UTC, jason-capsule42 approved these changes

2022-03-02 22:58 UTC, merged